#!/usr/bin/env bash
set -uo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/../lib/harness.sh"
SRC="${SBSHELL_SRC:-/src}"
UI="$SRC/openwrt/update_ui.sh"; CHECK="$SRC/openwrt/check_config.sh"
INPUT="$SRC/openwrt/manual_input.sh"; UPDATE="$SRC/openwrt/manual_update.sh"
DEFAULTS="$SRC/openwrt/set_defaults.sh"; INSTALL="$SRC/openwrt/install_singbox.sh"
TEMPLATE="$SRC/config_template/config_sb_Tun_fakeip.json"
CURRENT_URL="https://raw.githubusercontent.com/meiao123/public/refs/heads/main/singbox/configuration/1.2.x/config_sb_Tun_fakeip.json"
suite_begin "sing-box 1.14+ API Dashboard 兼容层"
assert_grep 'services\[\].type=api' "$UI" "UI 管理脚本声明新 API service 路径"
assert_grep 'api_dashboard_status() {' "$UI" "检测原生 Dashboard 的状态函数存在"
assert_grep '/dashboard/' "$UI" "使用 sing-box 原生 /dashboard/ 路径"
assert_grep 'cleanup_legacy_ui_automation' "$UI" "新格式会清理旧版 Clash UI 定时任务"
assert_grep 'api_dashboard_configured' "$UI" "新 API Dashboard 配置优先于旧版 UI 分支"
assert_grep 'secret 为空' "$UI" "新 API Dashboard 对空 secret 给出安全警告"
assert_grep 'api_block=\$(sed -n' "$CHECK" "配置检查脚本读取 services.api"
assert_grep '"api"' "$CHECK" "配置检查脚本包含 api service 类型匹配"
assert_grep 'auto_redirect' "$CHECK" "配置检查脚本识别 TUN auto_redirect"
suite_begin "当前 TUN FakeIP 配置默认入口"
assert_file "$TEMPLATE" "仓库包含当前 TUN FakeIP 模板"
assert_grep '"type": "api"' "$TEMPLATE" "模板使用 1.14+ API service"
assert_grep '"dashboard"' "$TEMPLATE" "模板启用原生 Dashboard"
assert_grep '"type": "fakeip"' "$TEMPLATE" "模板使用新的 fakeip DNS server"
assert_grep '"store_dns": true' "$TEMPLATE" "模板使用新的 cache_file.store_dns"
assert_grep '"auto_redirect": true' "$TEMPLATE" "模板使用 TUN auto_redirect"
assert_grep '"listen_port": 9090' "$TEMPLATE" "模板 API 监听端口为 9090"
suite_begin "配置输入/更新默认指向当前模板"
assert_grep "$CURRENT_URL" "$INPUT" "初始化配置在没有默认值时回退到当前 TUN 模板"
assert_grep "$CURRENT_URL" "$UPDATE" "手动更新配置在没有默认值时回退到当前 TUN 模板"
assert_grep "$CURRENT_URL" "$DEFAULTS" "默认参数脚本使用当前 TUN 模板地址"
suite_begin "OpenWrt TUN 环境依赖"
assert_grep 'kmod-nft-queue' "$INSTALL" "安装流程确保 NFQUEUE 所需的 kmod-nft-queue"
suite_end
